            - name: Mirror /tasks from FTP → repo
        run: |
          lftp "ftp://halaqaat.linuxproguru.com" -u "mdmunazir","${FTP_PASSWORD}" << 'EOF'
          set ssl:verify-certificate no
          mirror \
            --verbose \
            --only-newer \
            --delete \
            /tasks ./tasks
          quit
          EOF

        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}