    - name: Test FTP + lftp
      env:
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        sudo apt update
        sudo apt install -y lftp
        echo "Testing FTP connection..."
        lftp -u mdmunazir,"$FTP_PASSWORD" halaqaat.linuxproguru.com -e "
          set ssl:verify-certificate false;
          ls;
          quit
        "
