      - name: Mirror /tasks from FTP → repo
        run: |
          lftp -u "mdmunazir","${FTP_PASSWORD}" "halaqaat.linuxproguru.com" << 'EOF'
          set ssl:verify-certificate no
          mirror \
            --verbose \
            --only-newer \
            --delete \
            /www/halaqaat.linuxproguru.com/tasks ./tasks
          quit
          EOF


        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}